### ISSUE TITLE
User tree not started

### ISSUE THREAD

**Issue by Roger-Roger-debug** [mobinmob/void-66-services#155]
From my understanding you have to install the `scandir-66serv` package and then enable it for your user, so for me it would be `sudo 66-enable -t default scandir@roger`. However none of my trees get initialized much less started, although I enabled them.

I checked the [artix](https://wiki.artixlinux.org/Main/Suite66#User_services) wiki and it looks like it should work after that and the obarun wiki wants me to enable a `boot-user@` service, which doesn't exist.

**Comment by mobinmob** [comment]
There is a short and a long(er) answer regarding the support of user services :)
The short answer is that it is possible to use user services right now, but is is awkward. I am working on a complete solution, but it is not ready yet. I will document the process once I have something decent working.
The long answer is that I will like to support user services **fully**. That means services that only work while a specific user is logged in and stop on logout **and** services that start on login and _**linger**_ after logout.
The only way to correctly do both is to have some way to reliably track user sessions and run scripts on login-logout. _elogind_ and _consolekit2_ can do that, but I want something that can work even without them - I plan to support them in the future if possible, but not depend on them.
@Obarun has created a really nice tool for this that depends only on posix interfaces - [utlogd](https://framagit.org/Obarun/utlogd). I have done the packaging work already in the user-services branch of the [66-voidlinux ](https://codeberg.org/mobinmob/66-voidlinux/src/branch/user-services) repo. I hope I will have something usable in the following month.
The solution with not involve a boot-user@ module service, it will be much simpler and I will provide documentation for this.
If you wish to use user services right now, you need the scandir@user service enabled in the default tree and a script that with start your trees on login.

**Comment by Roger-Roger-debug** [comment]
I see, then everything is working as it should.
