### ISSUE TITLE
[oidentd] Wrong use of the exclamation mark

### ISSUE THREAD

**Issue by Obarun** [mobinmob/void-66-services#176]
> [environment]
> \# -S is for logging to stdout to use the per-service logger
> cmd_args=! -u nobody -g nogroup -S

According to https://web.obarun.org/software/66/latest/frontend.html#Section:%20%5Benvironment%5D, the exclamation mark must be stuck to the variable instead of the equal sign. In your case the exclamation mark has no effect.

So it should be:
`cmd_args=!-u nobody -g nogroup -S`
or
`cmd_args= !-u nobody -g nogroup -S`
or
`cmd_args =!-u nobody -g nogroup -S`
or
`cmd_args = !-u nobody -g nogroup -S`

same here https://github.com/mobinmob/void-66-services/blob/master/usr/share/66/service/lldpd

**Comment by mobinmob** [comment]
> > [environment]
> > # -S is for logging to stdout to use the per-service logger
> > cmd_args=! -u nobody -g nogroup -S
> 
> According to https://web.obarun.org/software/66/latest/frontend.html#Section:%20%5Benvironment%5D, the exclamation mark must be stuck to the variable instead of the equal sign. In your case the exclamation mark has no effect.
> 
> So it should be: `cmd_args=!-u nobody -g nogroup -S` or `cmd_args= !-u nobody -g nogroup -S` or `cmd_args =!-u nobody -g nogroup -S` or `cmd_args = !-u nobody -g nogroup -S`
> 
> same here https://github.com/mobinmob/void-66-services/blob/master/usr/share/66/service/lldpd

Thank you :) Ι think most of the services are correct - I will check and fix the rest!
