### ISSUE TITLE
Can't enable services

### ISSUE THREAD

**Issue by loFiWaterCat** [mobinmob/void-66-services#193]
After following the directions in https://github.com/mobinmob/void-66-services/blob/master/conf/void-66-conf.md, I have a system that boots with s6, but I cannot enable new services because 66-enable was unable to parse the service files.

An example:

```
$ 66-tree -ncE net
66-tree: info: Created successfully tree: net
66-tree: info: Enabled successfully tree: net
66-tree: info: Set successfully: net as default

$ 66-enable dhcpcd
66-enable: fatal: unable to parse service file: /usr/share/66/service/dhcpcd: or its dependencies
```

I would appreciate any guidance.

**Comment by mobinmob** [comment]
> After following the directions in https://github.com/mobinmob/void-66-services/blob/master/conf/void-66-conf.md, I have a system that boots with s6, but I cannot enable new services because 66-enable was unable to parse the service files.
> 
> An example:
> 
> ```
> $ 66-tree -ncE net
> 66-tree: info: Created successfully tree: net
> 66-tree: info: Enabled successfully tree: net
> 66-tree: info: Set successfully: net as default
> 
By following the instrustions a tree named default is already the current tree. No need to create one. Please try the default configuration first :)

> $ 66-enable dhcpcd
> 66-enable: fatal: unable to parse service file: /usr/share/66/service/dhcpcd: or its dependencies
> ```
> 
> I would appreciate any guidance.

Please provide the output from the following commands running as root:

(use a pastebin service if possible)

`66-intree -zg`

`66-enable -v4 dhcpcd`

`cat /usr/share/66/service/dhcpcd`

**Comment by loFiWaterCat** [comment]
Sorry for the format, but here's the termbin of all those commands.
https://termbin.com/m2hn

The default configuration is created by using the `66boot-initial-setup`, `66boot-storage-autoconf`, and the 
`66boot-rcdotconf` scripts correct?

I am a bit confused on how to create and manage a user tree. I was reading the Obarun's [beginner guide to 66](https://wiki.obarun.org/doku.php?id=66intro) which had these commands
```
# 66-tree -nE net
# 66-enable -t net dhcpcd wpa_supplicant ntpd
# 66-all -t net up
```
Is it done differently in void?

Let me know if you need any additional information.

**Comment by loFiWaterCat** [comment]
Additionally, is the "default" tree different than the current tree set by using the -c option for `66-tree`? And I forgot to mention that enabling dhcpcd from your instructions worked!

**Comment by mobinmob** [comment]
> Sorry for the format, but here's the termbin of all those commands. https://termbin.com/m2hn
> 
Thanks for the logs :)

```
66-enable(src/lib66/ssexec_enable.c: start_write(): 126): tracing: Service written successfully: dhcpcd
66-enable(src/lib66/ssexec_enable.c: ssexec_enable(): 361): info: Enabled successfully: dhcpcd
```
I do not see a problem there...

> The default configuration is created by using the `66boot-initial-setup`, `66boot-storage-autoconf`, and the `66boot-rcdotconf` scripts correct?
> 
Yep :)

> I am a bit confused on how to create and manage a user tree. I was reading the Obarun's [beginner guide to 66](https://wiki.obarun.org/doku.php?id=66intro) which had these commands
> 
> ```
> # 66-tree -nE net
> # 66-enable -t net dhcpcd wpa_supplicant ntpd
> # 66-all -t net up
> ```
> 
> Is it done differently in void?

I do not support a user tree in voidlinux. I will support user/session services eventually either with [utlogd](https://codeberg.org/mobinmob/66-voidlinux/pulls/2) or with [turnstile](https://github.com/void-linux/void-packages/pull/42771#discussion_r1137244742). Obarun has a different way of configuring the user session, that will not work well with voidlinux. 

The configuration I suggest and the _66boot-initial-setup_ implements created 3 trees: _boot_, `default` and `runit`.  All system-wide services can be enabled in the `default` tree. 
User/session services can be enabled using the scandir@ service but I do not yet have full support for properly automating the process on user login/logout. That is the reason the documentation does not refer to this.

> Let me know if you need any additional information.

**Comment by mobinmob** [comment]
> Additionally, is the "default" tree different than the current tree set by using the -c option for `66-tree`? And I forgot to mention that enabling dhcpcd from your instructions worked!

The default tree **is** the **current** one after `66boot-initial-setup`.
The naming mimics the one used in the voidlinux runit configuration.

**Comment by loFiWaterCat** [comment]
> I do not support a user tree in voidlinux. I will support user/session services eventually either with [utlogd](https://codeberg.org/mobinmob/66-voidlinux/pulls/2) or with https://github.com/void-linux/void-packages/pull/42771#discussion_r1137244742. Obarun has a different way of configuring the user session, that will not work well with voidlinux.

Since this is the case, all 66 commands should be run as sudo for now, correct? And thank you for the clarification.

**Comment by loFiWaterCat** [comment]
Alright, thank you for all the help so far, you've been amazing!

**Comment by mobinmob** [comment]
> Alright, thank you for all the help so far, you've been amazing!

Thank you for the feedback 😉
